# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nbelpois <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/15 14:25:08 by nbelpois          #+#    #+#              #
#    Updated: 2018/05/15 15:26:00 by nbelpois         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
CFLAGS = -Wall -Werror -Wextra
NAME = do-op
SRC = ft_atoi.c ft_putnbr.c ft_do_op.c ft_putchar.c ft_putstr.c main.c

all: 
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

.PHONY: clean

clean:
	/bin/rm -f $(NAME)


